### ISSUE TITLE
Add config option to enable/disable versioning

### ISSUE THREAD

**Issue by ejunker** [EscapeWork/laravel-asset-versioning#4]
Instead of checking if the environment is `local`, just add a config option to enable or disable the versioning. Then it will be more flexible and not assume that everybody uses the `local` environment. Users can then use Laravel's config system to configure which environments should use versioning.

**Comment by luisdalmolin** [comment]
That's a good idea. Will work on that.

**Comment by luisdalmolin** [comment]
Added in 0.3 version. Thanks!
